FROM python:3.7
ADD . /var/www/flask
VOLUME ["/var/www/flask"]
WORKDIR /var/www/flask
EXPOSE 8080
# RUN pip install -r requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
CMD uwsgi uwsgi.ini
